language: julia

julia:
  - 1.1

os:
  - linux

notifications:
  email: false

after_success:
  - julia --project -e 'using Pkg, Econometrics; cd(dirname(Pkg.pathof(Econometrics))); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder("."))'

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      codecov: true
      script:
        - julia --project -e 'using Pkg; Pkg.instantiate()'
        - julia --project docs/make.jl
      after_success: skip
