language: julia
matrix:
  fast_finish: true
  include:
    - os: linux
      julia: 1.3
    - os: osx
      julia: 1.3
    - os: windows
      arch: x64
      julia: 1.3
    - os: windows
      arch: x86
      julia: 1.3
codecov: true
notifications:
  email: false
jobs:
  include:
    - stage: "Documentation"
      julia: 1.3
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
