language: julia
os:
  - linux
  - osx
  - windows
julia:
  - 1.0
  - 1.2
  - 1.3
codecov: true
notifications:
  email: false
jobs:
  include:
    - os: windows
      arch: x86
      julia: 1.3
    - stage: "Documentation"
      os: linux
      julia: 1.3
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
