language: julia
julia: 1.3
codecov: true
notifications:
  email: false
jobs:
  include:
    - stage: "Test"
      matrix:
        fast_finish: true
        include:
          - os: linux
          - os: osx
          - os: windows
            arch: x64
          - os: windows
            arch: x86
    - stage: "Documentation"
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
