name: CI
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CONTRIBUTING.md'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - '.github/SUPPORT.md'
      - '.github/CompatHelper.yml'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'LICENSE.md'
      - 'README.md'
      - '.github/ISSUE_TEMPLATE'
      - '.github/CODE_OF_CONDUCT.md'
      - '.github/CONTRIBUTING.md'
      - '.github/pull_request_template.md'
      - '.github/SECURITY.md'
      - '.github/SUPPORT.md'
      - '.github/CompatHelper.yml'
  release:
    types:
      - created

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['^1.6.0-rc1']
        julia-arch: [x64]
        os: [ubuntu-20.04]
      matrix:
        arch: ${{ matrix.julia-arch }}
        version: ${{ matrix.julia-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-buildpkg@v0.1
      - uses: julia-actions/julia-runtest@v0.1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
